#!/bin/bash
#定义帮助函数
#检查运行环境，JDK,MAVEN
#定义获取NULS2.0运行环境函数
#定义获取模板函数
#定义打包函数

cd `dirname $0`
ROOT_PATH=`pwd`
NULS2_REPO="https://github.com/nuls-io/nuls-v2.git"
NULS2_BRANCH="chainbox"
NULS2_RUNTIME_DIR="NULS-WALLET-RUNTIME"
NULS2_REPO_DIR=".NULS2.0"

JAVA_MODULE_TEMP_REPO="https://github.com/nuls-io/nuls-module-template-java.git"

TEMPLATLIST="java"

help()
{
    cat <<- EOF
    Desc: NULS-engine 脚本程序
    Usage: ./tools
            -t <language> [folder name] 获取指定开发语言的模块程序模块 
                <language> 开发语言 ，如java
                [folder name] 下载到指定名字的目录下
            -r <folder name> 重新获取模块代码     
            -l 查看支持的模板列表    
            -n [模块目录...] 获取NULS2.0运行环境(从nuls-v2/nuls-engine分支拉) 默认构建6个核心模块，可以通过传入可选模块名称的方式添加可选模块
            -p <模块目录> [模块目录...]   集成指定模块到NULS2.0运行环境中
            -a 添加一个基础模块
            -d 移除一个基础模块
            -s 查看配置的待打包的基础模块列表            
            -h 查看帮助
            
EOF
    exit 0
}

getModuleItem(){
    while read line
    do
        pname=`echo $line | awk -F '=' '{print $1}'`
        pvalue=`awk -v a="$line" '
                        BEGIN{
                            len = split(a,ary,"=")
                            r=""
                            for ( i = 2; i <= len; i++ ){
                                if(r != ""){
                                    r = (r"=")
                                }
                                r=(r""ary[i])
                            }
                            print r
                        }
                    '`        
        if [ "${pname}" == $2 ]; then
            echo ${pvalue};
            return 1;
        fi
    done < $1
    return 0
}


#日志打印函数
echoRed() { echo $'\e[0;31m'$1$'\e[0m'; } #print red
echoGreen() { echo $'\e[0;32m'$1$'\e[0m'; } #print green
echoYellow() { echo $'\e[0;33m'$1$'\e[0m'; } #print yellow
log(){ #print date prefix and green
    now=`date "+%Y-%m-%d %H:%M:%S"`
    echoGreen "$now $@"
}

# 检查java版本 must be 11
checkJavaVersion(){
    JAVA="$JAVA_HOME/bin/java"
    if [ ! -r "$JAVA" ]; then
        JAVA='java'
    fi

    JAVA_EXIST=`${JAVA} -version 2>&1 |grep 11`
    if [ ! -n "$JAVA_EXIST" ]; then
            log "JDK version is not 11"
            ${JAVA} -version
            exit 0
    fi
}

checkMaven(){
    MAVEN_EXIST=`${MVN} -version 2>&1 |grep "Apache Maven"`
    if [ ! -n "$MAVEN_EXIST" ]; then
            log "maven not install"
            exit 0
    fi
}

checkJDKAndMaven(){
    checkJavaVersion
    # checkMaven
}

checkJDKAndMaven
WGET_EXIST=`wget -V 2>&1 |grep "GNU Wget"`
if [ -z "$WGET_EXIST" ]; then
    echoRed "not found wget , install wget "
    exit 0;
fi

PACKAGE_CONFIG="`pwd`/.package.ncf"

#编辑.package.ncf
updatePackage(){
    c="sed -n '/^$1/p' $PACKAGE_CONFIG"
    has=`eval $c`;
    if [ -n "$has" ];
    then
        os=`uname`
        if [ "$os" == "Darwin" ];
        then
            eval "sed -i '' 's/^$has/$1=$2/' $PACKAGE_CONFIG"
        else
            eval "sed -i 's/^$has/$1=$2/' $PACKAGE_CONFIG"
        fi
    else
        if [ $2 == "1" ]; then
            echo "${1}=1" >> $PACKAGE_CONFIG
            echo "" >> $PACKAGE_CONFIG
        fi
    fi
    # exit 0
}

showPackageModule(){
    log "=========================="
    log "package module list"
    while read line
    do
        TEMP=`echo $line|grep -Eo '\[.+\]'`
        if [ -z "$TEMP" ]; then
            isPackage=`echo $line |grep "=1"`
            if [ -n "$isPackage" ]; then
                log "---->$line" | awk -F '=' '{print $1}'
            fi
        fi
    done < $PACKAGE_CONFIG
    log "=========================="
}

showTemplateList(){
    while read line
    do
        
        TEMP=`echo $line|grep -Eo '\[.+\]'`
        if [ -z "$TEMP" ]; then
            pname=`echo $line | awk -F '=' '{print $1}'`
            echo $pname
            gitUrl=`getModuleItem "${ROOT_PATH}/template" ${pname}`
            # curl "${gitUrl}/.describe"
            # isPackage=`echo $line |grep "=1"`
            # if [ -n "$isPackage" ]; then
            #     log "---->$line" | awk -F '=' '{print $1}'
            #fi
        fi
        
    done < "${ROOT_PATH}/template"
}

#检查是否已经clone了nuls2.0
initAndUpdateNulsRuntime()
{
    MAVEN_EXIST=`mvn -version 2>&1 |grep "Apache Maven"`
    # echo $MAVEN_EXIST
    if [ -z "$MAVEN_EXIST" ]; then
        if [ ! -d "./lib" ]; then
            mkdir ./lib
        fi    
        if [ ! -d "./lib/maven" ]; then
            cd ./lib
            WGET_EXIST=`wget -V 2>&1 |grep "GNU Wget"`
            if [ -z "$WGET_EXIST" ]; then
                echoRed "not found wget , install wget "
                exit 0;
            fi
            wget http://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
            tar -xvf ./apache-maven-3.6.1-bin.tar.gz
            mv ./apache-maven-3.6.1 ./maven
            cd ..
        fi
        path=`pwd`
        export MAVEN_HOME=${path}/lib/maven
        export PATH=${PATH}:${MAVEN_HOME}/bin
    fi
    if [ ! -d "$NULS2_REPO_DIR" ]; 
    then
        git clone $NULS2_REPO $NULS2_REPO_DIR
        cd $NULS2_REPO_DIR
        git checkout $NULS2_BRANCH
    else
        cd $NULS2_REPO_DIR
        git pull         
    fi
    if [ ! -f "${PACKAGE_CONFIG}" ]; then
        cp "./build/package-base.ncf" ${PACKAGE_CONFIG}
        #statements
    fi
    len=$#
    for ((i=2;i<=$len;i++));do
        module=`eval echo '$'"$i"`
        # echo $module
        updatePackage $module 1
    done  
    cp ${PACKAGE_CONFIG} ./.package.ncf
    ./package -a "mykernel"
    ./package -N -o "../$1"
    cd ..
    # rm -rf $NULS2_REPO_DIR
}

getModuleTemplate(){
    templateName=$1
    dirName=$2
    if [ -z "$dirName" ]; then
        dirName="$1"
    fi
    gitUrl=`getModuleItem ./template $templateName`
    if [ -z "$gitUrl" ]; then
        #statements 
        echo "not found template : $templateName"
        echo "template list : ${TEMPLATLIST}"
        exit 0
    fi
    echo $gitUrl
    git clone $gitUrl $dirName
    cd $dirName
    if [ -x ./init.sh ]; then 
        ./init.sh $dirName
        rm -f ./init.sh
    fi
    cat README.md
    #rm -rf .git

}

updateTemplate(){
    module=$1
    if [ ! -d "${module}" ]; then
        echo "not found module folder"
        exit 0
    fi
    cd $module
    git pull
    ./package
}

packageToNuls(){
    initAndUpdateNulsRuntime "./NULS-WALLET"
    for module in $@
    do
        # module=$1
        echo "packing ${module}"
        if [ ! -d $module ]; then
            echo "wrong module folder"
            exit 0;
        fi
        cd $module
        if [ ! -d "outer" ]; then
            if [ -f "./package" ]; then
                ./package
            fi
            if [ ! -d "outer" ]; then
                echo "not found outer folder"
                exit 0
            fi
            
        fi
        if [ ! -f "outer/Module.ncf" ]; then
            echo "not found Module.ncf"
            exit 0
        fi
        moduleName=`getModuleItem  "outer/Module.ncf" "APP_NAME"`;
        version=`getModuleItem  "outer/Module.ncf" "VERSION"`;
        if [ -z "$moduleName" ]; then
            echo "must setting APP_NAME"
            exit 0
        fi
        if [ -z "$version" ]; then
            echo "must setting VERSION"
            exit 0
        fi
        cd ..
        
        if [ ! -d "./NULS-WALLET/Modules/Nuls/$moduleName" ]; then
            mkdir "./NULS-WALLET/Modules/Nuls/$moduleName"
        fi
        if [ -d "./NULS-WALLET/Modules/Nuls/$moduleName/$version" ]; then
            rm -rf "./NULS-WALLET/Modules/Nuls/$moduleName/$version"
        fi
        mkdir "./NULS-WALLET/Modules/Nuls/$moduleName/$version"
        cp -r ${module}/outer/* "./NULS-WALLET/Modules/Nuls/$moduleName/$version"
        echo "copy ${module}/outer/ to ./NULS-WALLET/Modules/Nuls/$moduleName/$version"
        # echo $moduleName
        echo $moduleName >> ./NULS-WALLET/.modules
        echo "package ${module} finish"
    done
}


while getopts nt:p:ha:r:sld: name
do
            case $name in
            p)     
                   modules=()
                   len=$#
                   for ((i=$OPTIND - 1;i<=$len;i++));do
                       dir=`eval echo '$'"$i"`
                       modules[${#modules[@]}]=$dir
                   done    
                   packageToNuls ${modules[@]/\//}
                   exit
                   ;;
            t)     
                   dir=`eval echo '$'"$OPTIND"`
                   getModuleTemplate "$OPTARG" "$dir"
                   exit 0
                   ;;
            r)     updateTemplate "$OPTARG"     
                   ;;  
            n)     modules=()
                   len=$#
                   for ((i=$OPTIND - 1;i<=$len;i++));do
                       dir=`eval echo '$'"$i"`
                       modules[${#modules[@]}]=$dir
                   done   
                   initAndUpdateNulsRuntime $NULS2_RUNTIME_DIR ${modules[@]}
                   exit 0
                   ;;
            a)     updatePackage "$OPTARG" 1
                   exit 0
                   ;;
            d)     updatePackage "$OPTARG" 0
                   exit 0
                   ;;
            s)     showPackageModule
                   ;;
            l)     showTemplateList ;;       
            h)     help
                   exit 0
                   ;;
            ?)     exit 2;;
           esac
done




